version: "3.9"

services:
  app:
    build: ./php
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html/src
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:8.0.36
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: latihan
      MYSQL_USER: userku        # tetap ini
      MYSQL_PASSWORD: passku     # tetap ini
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  web:
    image: nginx:1.27-alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
